<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Amirthavahini08" failures="2" tests="5" name="Test" time="10.21" errors="0" timestamp="2025-06-26T09:41:53 IST">
  <testcase classname="com.tests.AssertionsDemo" name="myTest" time="0.014">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [true] but found [false]
at com.tests.AssertionsDemo.myTest(AssertionsDemo.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- myTest -->
  <testcase classname="com.tests.AnnotationsDemo" name="openApplication" time="0.001">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at com.tests.AnnotationsDemo.openApplication(AnnotationsDemo.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- openApplication -->
  <testcase classname="com.tests.AnnotationsDemo" name="login" time="0.0">
    <skipped/>
  </testcase> <!-- login -->
  <testcase classname="com.tests.AnnotationsDemo" name="closeApp" time="5.013"/>
  <testcase classname="com.tests.LoginTest" name="login" time="1.216"/>
</testsuite> <!-- Test -->
